name: Buildozer Android

on:
  push:
    branches:
      - main # Or master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip libtool zlib1g-dev libncurses5-dev
          pip install --upgrade pip
          pip install buildozer
          pip install kivy
          pip install matplotlib

      - name: Install Android SDK tools
        run: |
          cd /home/runner
          mkdir android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-8597394_latest.zip
          unzip commandlinetools-linux-8597394_latest.zip -d android-sdk
          rm commandlinetools-linux-8597394_latest.zip
          export PATH="$PATH:/home/runner/android-sdk/cmdline-tools/latest/bin"
          sdkmanager "build-tools;33.0.0" "platforms;android-33" "platform-tools"

      - name: Build Android APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ServiClick-APK
          path: bin/*.apk
