name: Buildozer Android

on:
  push:
    branches:
      - main # O master, si esa es tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Buildozer and Kivy
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip libtool zlib1g-dev libncurses5-dev
          pip install --upgrade pip
          pip install buildozer
          pip install cython
          pip install kivy matplotlib

      - name: Build Android APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ServiClick-APK
          path: bin/*.apk
