name: Buildozer Android (Manual SDK/NDK)

on:
  push:
    branches:
      - main # O master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip libtool zlib1g-dev libncurses5-dev
          pip install --upgrade pip
          pip install buildozer cython
          pip install kivy matplotlib

      - name: Install Android SDK and NDK
        run: |
          export ANDROID_HOME=$HOME/Android/sdk
          mkdir -p $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q commandlinetools-linux-11076708_latest.zip -d $ANDROID_HOME/cmdline-tools/latest
          rm commandlinetools-linux-11076708_latest.zip

          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses --sdk_root=$ANDROID_HOME > /dev/null
          
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;33.0.0" "platforms;android-33" "platform-tools" --sdk_root=$ANDROID_HOME
          
          export ANDROID_NDK_ROOT=$HOME/.buildozer/android/platform/android-ndk-r25b
          
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$ANDROID_NDK_ROOT" >> $GITHUB_ENV
          
      - name: Build Android APK
        run: |
          buildozer android debug
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ServiClick-APK
          path: bin/*.apk
